---

- name: Install neovim
  become: yes
  package: 
    name: neovim
    state: latest

- name: Link configs
  file:
    src: "{{ dotdir }}/nvim"
    dest: "{{ user_home }}/.config/nvim"
    state: link

- name: Install dependencies
  become: yes
  package:
    name:
      - ccls
      - yarn
      - npm
      - cmake
    state: present

- name: Install nvim plugins
  shell: 'nvim --headless +PlugInstall +qall'
